insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (1, 19, 'Chão', 'Shtip', '9:44 PM', '10:22 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (2, 25, 'Wyszki', 'Gulyantsi', '5:31 PM', '10:02 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (3, 14, 'Pidsandawan', 'Sukarame', '6:53 PM', '10:29 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (4, 11, 'Fagersta', 'Bromont', '4:43 PM', '4:12 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (5, 13, 'Qianjin', 'Roissy Charles-de-Gaulle', '2:02 PM', '4:35 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (6, 2, 'Praszka', 'Heishan', '10:39 PM', '12:58 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (7, 17, 'Oliveira', 'Buckland', '7:25 AM', '4:02 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (8, 10, 'Tangyu', 'Yashkul’', '12:26 PM', '9:39 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (9, 20, 'Tyresö', 'Tartagal', '6:12 AM', '9:35 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (10, 24, 'Reszel', 'La Dorada', '11:11 AM', '11:47 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (11, 4, 'Anticala', 'Wushan', '8:28 PM', '6:58 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (12, 12, 'Nema', 'Bailu', '6:23 PM', '8:16 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (13, 17, 'Xilin', 'Czerniejewo', '6:20 PM', '1:06 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (14, 3, 'Taihe', 'Jianqiao', '10:15 AM', '7:05 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (15, 6, 'Kiruru', 'Hesi', '3:29 AM', '7:50 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (16, 16, 'Strawczyn', 'Horad Barysaw', '12:26 PM', '9:14 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (17, 10, 'Lanckorona', 'Karvia', '11:44 AM', '10:22 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (18, 5, 'Monsanto', 'Hevlín', '12:50 PM', '4:01 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (19, 4, 'Warburton', 'Carvalhal Redondo', '2:41 PM', '12:11 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (20, 22, 'Beaconsfield', 'Milano', '5:47 PM', '1:12 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (21, 15, 'Siteki', 'Lixi', '11:12 PM', '1:22 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (22, 22, 'Vostryakovo', 'Jaroměř', '2:58 PM', '1:03 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (23, 23, 'Schengen', 'Daqin Tal', '5:48 PM', '10:33 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (24, 18, 'Nāḩiyat Baḩār', 'Tiedonglu', '5:27 AM', '9:02 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (25, 23, 'San José Poaquil', 'Mokronog', '5:43 PM', '3:29 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (26, 1, 'Totness', 'Chambellan', '2:16 PM', '11:24 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (27, 13, 'Suban', 'Margasari', '6:01 PM', '11:10 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (28, 3, 'Balayang', 'Saint Petersburg', '5:50 PM', '8:47 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (29, 19, 'Cachipay', 'Miao’ertan', '11:02 AM', '3:45 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (30, 15, 'Ongi', 'Taluncemara', '11:34 PM', '1:15 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (31, 18, 'La Roxas', 'Agbannawag', '2:34 AM', '2:14 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (32, 3, 'Indianapolis', 'Toronto', '10:01 AM', '10:53 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (33, 17, 'Serzedelo', 'Ninh Hòa', '7:57 AM', '10:21 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (34, 22, 'Huanren', 'Dongjiang Matoukou', '6:55 PM', '8:27 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (35, 25, 'Luoqi', 'Hejiadong', '5:36 AM', '8:16 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (36, 1, 'Balbalan', 'Oslo', '6:25 PM', '1:12 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (37, 12, 'Vakhtan', 'Culeng', '3:57 PM', '4:29 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (38, 10, 'Ituberá', 'Bressuire', '8:45 PM', '8:01 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (39, 2, 'Kedatuan', 'Arıqıran', '5:19 AM', '9:33 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (40, 10, 'Dingjia', 'Saint Paul', '1:58 PM', '9:23 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (41, 3, 'San Rafael', 'Zbůch', '2:20 PM', '12:50 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (42, 10, 'Oullins', 'Marapat', '3:03 PM', '1:48 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (43, 10, 'Las Vegas', 'Jönköping', '9:09 AM', '8:28 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (44, 18, 'Sławatycze', 'Fagersta', '10:30 AM', '4:29 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (45, 25, 'Mt Peto', 'Al Qārah', '7:46 PM', '7:57 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (46, 17, 'Senangkhanikhom', 'Shiogama', '4:32 AM', '4:06 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (47, 6, 'Shtip', 'Żyraków', '12:56 AM', '12:33 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (48, 18, 'Lianglin', 'Caldas da Rainha', '2:38 AM', '7:48 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (49, 4, 'Dasht-e Qal‘ah', 'Shangshuai', '4:56 PM', '12:56 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (50, 14, 'Tarouca', 'Rontu', '11:28 PM', '4:55 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (51, 2, 'Jiaozhou', 'Jumpangdua', '11:30 AM', '10:32 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (52, 19, 'Achoma', 'Yilkiqi', '7:37 AM', '6:38 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (53, 12, 'Sotomayor', 'Bang Sao Thong', '3:40 AM', '1:38 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (54, 10, 'Gävle', 'Bayt ‘Ūr at Taḩtā', '9:51 AM', '8:17 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (55, 18, 'Taguisa', 'Margahayu', '6:22 PM', '11:56 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (56, 2, 'Sumuran', 'Banyumas', '12:35 PM', '10:48 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (57, 16, 'Minle', 'Xinzhuang', '7:33 PM', '9:29 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (58, 13, 'Mīrpur Māthelo', 'Sibinal', '8:45 PM', '5:37 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (59, 22, 'Casigua El Cubo', 'Xiangba', '5:46 AM', '9:52 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (60, 22, 'Kon Dơng', 'Taling', '4:08 PM', '1:12 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (61, 9, 'Fuming', 'Góra', '3:37 PM', '4:06 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (62, 21, 'Nijmegen', 'Kazanskaya', '2:00 PM', '8:39 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (63, 8, 'Ciputih', 'Zavolzh’ye', '11:14 AM', '7:37 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (64, 24, 'Viitasaari', 'Olleros', '8:50 AM', '1:55 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (65, 20, 'Renhe', 'Kedungcangkring', '10:36 AM', '6:10 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (66, 8, 'Dayong', 'Aranos', '11:54 PM', '9:52 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (67, 10, 'Daszewice', 'Pontevedra', '6:49 PM', '1:53 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (68, 24, 'Muyuka', 'Tyoply Stan', '7:58 AM', '10:09 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (69, 23, 'Cordeiro', 'Boju', '9:07 PM', '4:18 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (70, 5, 'Tanahwangko', 'Huashu', '5:22 AM', '11:46 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (71, 3, 'Jiefangyan', 'Baishan', '5:28 PM', '6:57 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (72, 17, 'Issia', '‘Attīl', '3:47 PM', '3:19 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (73, 8, 'Mazamet', 'Brzeźnica', '12:29 PM', '10:29 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (74, 7, 'Colcabamba', 'Chancay', '1:00 PM', '4:39 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (75, 14, 'Sandachō', 'Gnojnik', '8:39 AM', '11:28 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (76, 6, 'Riosucio', 'Jiangkou', '8:24 AM', '4:30 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (77, 7, 'Roanne', 'Matagbak', '2:55 PM', '4:45 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (78, 5, 'Kurlovo', 'Santol', '10:08 PM', '9:26 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (79, 23, 'Baoziba', 'Tulsa', '1:03 AM', '1:44 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (80, 12, 'Bergem', 'Pringsewu', '9:35 AM', '7:13 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (81, 6, 'Khuzhir', 'Sapu Padidu', '6:20 PM', '4:38 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (82, 24, 'Telukpakedai', 'Söderhamn', '3:26 PM', '2:17 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (83, 5, 'Khvalovo', 'San Jorge', '2:33 AM', '2:07 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (84, 20, 'Heshan', 'Pacajus', '4:20 AM', '9:02 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (85, 17, 'Senduro', 'Ostrožská Lhota', '5:30 PM', '1:39 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (86, 17, 'Täby', 'Aldeia de Além', '12:23 PM', '1:22 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (87, 11, 'Lyon', 'Apucarana', '6:48 AM', '5:55 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (88, 22, 'Bouarouss', 'Taphan Hin', '3:52 AM', '4:46 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (89, 5, 'Muleba', 'Nijmegen', '2:10 AM', '9:33 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (90, 7, 'Colatina', 'Klimovsk', '5:29 AM', '8:00 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (91, 18, 'Corga', 'Łętownia', '12:09 PM', '3:09 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (92, 16, 'Damatulan', 'Gejiu', '7:50 AM', '3:39 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (93, 15, 'Qincheng', 'Candoni', '9:08 AM', '9:13 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (94, 14, 'Carletonville', 'Mzuzu', '7:55 AM', '11:51 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (95, 19, 'Río Tercero', 'Yujiao', '7:58 PM', '5:23 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (96, 16, 'Zhouxi', 'Cravo Norte', '8:45 PM', '12:36 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (97, 10, 'Limón', 'Dŭstí', '2:39 PM', '12:47 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (98, 10, 'Město', 'Kostrzyn nad Odrą', '5:42 PM', '12:54 AM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (99, 8, 'Trelleborg', 'Kimméria', '5:24 PM', '3:44 PM');
insert into flights (id, airplaneid, departure, arrival, departuretime, arrivaltime) values (100, 2, 'Sacanche', 'Molinos', '11:31 AM', '11:55 AM');
